"""Add consumer_message and message_color columns to case table

Revision ID: 15634b282662
Revises: 
Create Date: 2024-05-31 21:20:55.886916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15634b282662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumer_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('message_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('message_color')
        batch_op.drop_column('consumer_message')

    # ### end Alembic commands ###
