"""Add introduction column to companies table

Revision ID: 9b86132a32d2
Revises: ffb1d878a600
Create Date: 2024-05-31 21:55:27.334386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b86132a32d2'
down_revision = 'ffb1d878a600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('introduction')

    # ### end Alembic commands ###
